//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::accesses::Entity as Accesses;
pub use super::attachments::Entity as Attachments;
pub use super::o_auth2_sessions::Entity as OAuth2Sessions;
pub use super::roles::Entity as Roles;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
