//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use axum_typed_multipart::TryFromField;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(
    Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "access_level_enum")]
pub enum AccessLevelEnum {
    #[sea_orm(string_value = "View")]
    View,
    #[sea_orm(string_value = "AddSolution")]
    AddSolution,
    #[sea_orm(string_value = "Edit")]
    Edit,
    #[sea_orm(string_value = "AddUser")]
    AddUser,
    #[sea_orm(string_value = "FullAccess")]
    FullAccess,
}
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    ToSchema,
    TryFromField,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "attachment_type_enum"
)]
pub enum AttachmentTypeEnum {
    #[sea_orm(string_value = "Description")]
    Description,
    #[sea_orm(string_value = "DueDate")]
    DueDate,
    #[sea_orm(string_value = "File")]
    File,
    #[sea_orm(string_value = "Url")]
    Url,
    #[sea_orm(string_value = "Text")]
    Text,
    #[sea_orm(string_value = "Tip")]
    Tip,
    #[sea_orm(string_value = "Hint")]
    Hint,
    #[sea_orm(string_value = "Warning")]
    Warning,
    #[sea_orm(string_value = "Progress")]
    Progress,
    #[sea_orm(string_value = "Importance")]
    Importance,
}
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "task_visibility_enum"
)]
pub enum TaskVisibilityEnum {
    #[sea_orm(string_value = "Private")]
    Private,
    #[sea_orm(string_value = "Public")]
    Public,
    #[sea_orm(string_value = "Paid")]
    Paid,
}
