logger:
  enable: true
  pretty_backtrace: true # sets RUST_BACKTRACE=1
  level: debug # trace, debug, info, warn or error.
  format: compact # compact, pretty or json
  # By default the logger has filtering only logs that came from your code or logs that came from `loco` framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace

server:
  port: 5150
  binding: localhost
  host: https://taskhub.linerds.us
  middlewares:
    cors:
      enable: true
      allow_origins:
        - https://task-hub-tau-one.vercel.app
        - https://93.205.70.240
      allow_headers:
        - Content-Type
      allow_methods:
        - GET
        - PUT
        - POST
        - PATCH
        - DELETE
        - OPTIONS
      max_age: 3600

workers:
  mode: BackgroundAsync

mailer:
  smtp:
    enable: true
    # hello_name: # default is the machine's hostname
    host: smtp.gmail.com
    port: 587
    secure: true
    auth:
      user: {{ get_env(name="SMTP_USER", default="no_user") }}
      password: {{ get_env(name="SMTP_PASSWORD", default="no_password") }}

# Initializers Configuration
initializers:
  openapi:
    redoc:
      url: /redoc
    scalar:
      url: /scalar
    swagger:
      url: /swagger
      spec_json_url: /api-docs/openapi.json # spec_json_url is required for swagger-ui
  oauth2:
    authorization_code: # Authorization code grant type
      - client_identifier: google # Identifier for the OAuth2 provider. Replace 'google' with your provider's name if different, must be unique within the oauth2 config.
        client_credentials:
          client_id: {{get_env(name="OAUTH_CLIENT_ID", default="oauth_client_id")}} # Replace with your OAuth2 client ID.
          client_secret: {{get_env(name="OAUTH_CLIENT_SECRET", default="oauth_client_secret")}} # Replace with your OAuth2 client secret.
        url_config:
          auth_url: {{get_env(name="AUTH_URL", default="https://accounts.google.com/o/oauth2/auth")}} # authorization endpoint from the provider
          token_url: {{get_env(name="TOKEN_URL", default="https://www.googleapis.com/oauth2/v3/token")}} # token endpoint from the provider for exchanging the authorization code for an access token
          redirect_url: {{get_env(name="REDIRECT_URL", default="http://localhost:5150/api/oauth2/google/callback/jwt")}} # server callback endpoint for the provider
          profile_url: {{get_env(name="PROFILE_URL", default="https://openidconnect.googleapis.com/v1/userinfo")}} # user profile endpoint from the provider for getting user data
          scopes:
            - {{get_env(name="SCOPES_1", default="https://www.googleapis.com/auth/userinfo.email")}} # Scopes for requesting access to user data
            - {{get_env(name="SCOPES_2", default="https://www.googleapis.com/auth/userinfo.profile")}} # Scopes for requesting access to user data
        cookie_config:
          protected_url: {{get_env(name="PROTECTED_URL", default="http://localhost:5150/api/oauth2/protected")}} # Optional for jwt - For redirecting to protect url in cookie to prevent XSS attack
        timeout_seconds: 600 # Optional, default 600 seconds

database:
  uri: {{ get_env(name="DATABASE_URL", default="postgres://loco:loco@localhost:5432/task_hub_development") }}
  enable_logging: false # When enabled, the sql query will be logged.
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT", default="500") }}
  idle_timeout: {{ get_env(name="DB_IDLE_TIMEOUT", default="500") }}
  min_connections: {{ get_env(name="DB_MIN_CONNECTIONS", default="1") }}
  max_connections: {{ get_env(name="DB_MAX_CONNECTIONS", default="1") }}
  auto_migrate: true
  # Truncate database when application loaded. This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_truncate: false
  # Recreating schema when application loaded.  This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_recreate: false

auth:
  jwt:
    secret: {{ get_env(name="JWT_SECRET", default="AL2CqptpFl2vNCzswvEK") }}
    expiration: 604800 # 7 days
    location:
      from: Cookie
      name: auth_token

settings:
  frontend: "task-hub-tau-one.vercel.app"
  # backend: "taskhub.linerds.us"
  backend: "localhost"
